### ISSUE TITLE
Dark Archon shoulder guard position messed up

### ISSUE THREAD

**Issue by Onixiya** [Talv/m3addon#39] opened 2021-10-06 01:20 UTC
![Capture1](https://user-images.githubusercontent.com/29950414/136125562-e4ff5da0-d554-431a-8ae4-cb5725f34206.png)
File is already in the game files, name is Void_DarkArchon.m3, a issue with bones most likely as it gets reset to the correct position upon going into edit mode for the mesh
![Capture1](https://user-images.githubusercontent.com/29950414/136125690-af3dc104-75eb-430a-80cf-bd12c5bda1c6.png)

**Comment by Solstice245** [comment] 2023-09-15 22:06
This issue has been reported already with regards to a different model. (Duplicate of #4 )

**Closed as completed by Solstice245** 2023-09-15 22:06 UTC
