### ISSUE TITLE
Does not work with 2.82

### ISSUE THREAD

**Issue by CommanderChuter** [Talv/m3addon#20] opened 2020-02-23 02:41 UTC
The addon will load in, but when you hit the check box to enable it, you get the error posted bellow.

![m3addon_error](https://user-images.githubusercontent.com/61368449/75102595-58743200-55ab-11ea-8890-143bd4b591cf.PNG)

**Comment by CommanderChuter** [comment] 2020-02-23 02:43
Here is a better image.
![m3addon_error_better](https://user-images.githubusercontent.com/61368449/75102612-9c673700-55ab-11ea-9612-fe8e8456ff42.PNG)

**Comment by CommanderChuter** [comment] 2020-02-23 03:34
The problem seems to be with aliased functions.
Everything seems to work if I replace all of the aliased functions with direct calls to the shared module.

**Comment by Talv** [comment] 2020-03-21 08:39
Hmm, I'm unable to reproduce it. What version of 2.82 is it exactly? I've tested on:
```
$ blender --version
Blender 2.82 (sub 7)
	build date: 2020-02-28
	build time: 18:18:05
	build commit date: 2020-02-13
	build commit time: 11:37
	build hash: 5b416ffb848e
```
and experienced no such problems.

Also, I've got some reports from other people that addon runs fine on 2.82.

**Comment by CommanderChuter** [comment] 2020-03-22 17:19
Here is my build info (windows 10)

Blender 2.82 (sub 7) System Information 

version: 2.82 (sub 7), branch: master,
commit date: 2020-02-12 16:20,
hash: 77d23b0bd76f,
type: Release

build date: 2020-02-13, 01:56:46
platform: Windows

**Comment by CommanderChuter** [comment] 2020-03-22 17:20
Also the problem was in \_\_init\_\_.py line 783-786:

#selectBone = shared.selectBone
#removeBone = shared.removeBone
#selectOrCreateBone = shared.selectOrCreateBone
#selectBoneIfItExists = shared.selectBoneIfItExists

These seemed to be aliased functions, that were not resolving.
I fixed the problem by replacing the alias with the full name.

**Comment by Talv** [comment] 2020-03-22 22:20
I don't quite understand why Python would complain about it.. but these aliases are indeed redundant, and there's better way to go about this.

The only reason I don't simply change all function calls to use `shared.` prefix is because this addon has a ton of legacy code. So I'm trying to not modify unrelated code - just to keep the commit history clean (for purposes like git blame etc.).

Anyway, whenever you get a chance please test if following commit fixes the problem: 2ae27f312b456185bfa4bdee62b3273a444adafa . As I'm unable to reproduce it on my end.

**Comment by RoscoeTheDog** [comment] 2020-06-07 01:08
I have run into the same issues, using blender 2.83 on Windows 10 x64

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\m3addon-master\__init__.py", line 67, in <module>
    from .shared import selectBone, removeBone, selectOrCreateBone, selectBoneIfItExists
ImportError: cannot import name 'selectBone' from 'm3addon-master.shared' (C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\m3addon-master\shared.py)


```

**Comment by Talv** [comment] 2021-04-18 12:10
These errors don't make sense at all. I'm suspecting that it could be caused by another version of m3addon installed before (like one of the existing forks), or some quirks like that.

If someone still experiences this I'd advise to do manual install to `m3addon` folder, instead of `m3addon-master` (which is created by Github zip packager, and then picked up by Blender when installing addon from the zip file). And to make sure there are no other copies of m3addon.

Closing until there's a way for us to reproduce this.

**Closed as completed by Talv** 2021-04-18 12:10 UTC
