### ISSUE TITLE
Broken bone import for Queens Animations

### ISSUE THREAD

**Issue by DeffOS** [Talv/m3addon#46] opened 2023-09-15 21:32 UTC
Observed on all queen reskins
![image](https://github.com/SC2Mapster/m3addon/assets/68462654/51ece606-f474-4fea-a0da-58b31f76b5ca)

**Comment by DeffOS** [comment] 2023-09-15 21:39
Looks like Bone19/Bone20/Bone21/Bone23 have fully inverted rotations in animation itself

**Comment by DeffOS** [comment] 2023-09-15 22:06
By setting connected with parent to all bones and invert root of wing it will set in place properly, albeit inverted by scale
![image](https://github.com/SC2Mapster/m3addon/assets/68462654/3d4e112d-fb7e-4708-99cc-d417ead89304)
![image](https://github.com/SC2Mapster/m3addon/assets/68462654/7d90ec60-bd60-4b2f-b6a0-9036e78ddeeb)

**Comment by Solstice245** [comment] 2023-09-15 22:07
This issue has been reported already with regards to a different model. (Duplicate of #4 )
That issue's thread has some comments you might find useful as well.

**Closed as completed by Solstice245** 2023-09-15 22:07 UTC
